spring:
  application:
    name: legalchecker

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.legalchecker: DEBUG
